version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/node_modules/.cache
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - VUE_APP_API_URL=http://backend:5000 

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

networks:
  app-network:
    driver: bridge